### ISSUE TITLE
run bisecting bugs for sqlright_sqlite TLP failed

### ISSUE THREAD

**Issue by AlexWonga** [PSU-Security-Universe/sqlright#2]
when i run the shell "run_sqltie_bisecting.sh" in sqlright/sqlite/scripts, i got an error like this: 
![image](https://user-images.githubusercontent.com/52265703/198472232-7dd1dc3c-96c8-467a-8c24-70845794dc5b.png)
how to fix it?

**Comment by SteveLeungYL** [comment]
Thank you for the error information. The bug is fixed in commit: 0eca86543c.

To patch the code, you need to 

1. pull the latest code changes from this github repo. 
2. rerun the `setup_sqlite.sh` script in `SQLite/scripts`. 
3. rerun the command `bash run_sqlite_bisecting.sh SQLRight  -O TLP` to bisect the detected bugs. 

Please let us know if you have more questions.

**Comment by AlexWonga** [comment]
thank you very much
