### ISSUE TITLE
How to change the target SQLite version？

### ISSUE THREAD

**Issue by doriscullen** [PSU-Security-Universe/sqlright#4]
Dear developers, 
I'm trying to apply your valuable work in my research, and I come to this question: If I want to test the latest version of SQLite (version-3.43.2), which files should I modify before building the docker image?

My understanding is, in the Dockerfile, I should add `RUN git checkout version-3.43.2` after cloning SQLite, as shown:
<img width="420" alt="image" src="https://github.com/PSU-Security-Universe/sqlright/assets/61410303/4d1aa8d6-d0ec-471b-97cf-528e97dc098b">
and
<img width="600" alt="image" src="https://github.com/PSU-Security-Universe/sqlright/assets/61410303/43ddda1d-917b-4b54-a7c0-d6ad98fbe91e">
Did I do it right?

Besides, my question is, why `SQLite/docker/scripts/run_sqlright_sqlite_fuzzing_helper.sh` executes `cd /home/sqlite/sqlite` `git pull origin master`? If I want to test a specified version (like 3.43.2), should I delete these statements?

Many thanks!

**Comment by SteveLeungYL** [comment]
Yes. What you do is correct. Change the `Dockerfile` and remove the `pull` command, then you can test specific SQLite3 version as you demand. 

The `git pull origin master` line from the `run_sqlright_sqlite_fuzzing_helper.sh` file is redundant here, since we only want to test a specific version of the SQLite3 instead of testing the latest `master`. 

Thank you for your interest in our work!
